export { default as FBadge } from '@/components/badge'
export { default as FBarrage } from '@/components/barrage'
export { default as FButton } from '@/components/button'
export { default as FCopyText } from '@/components/copy-text'
export { default as FCoupon } from '@/components/coupon'
export { default as FEmpty } from '@/components/empty'
export { default as FIcon } from '@/components/icon'
export { default as FImg } from '@/components/img'
export { default as FInput } from '@/components/input'
export { default as FLoading } from '@/components/loading'
export { default as FLogin } from '@/components/login'
export { default as FMessage } from '@/components/message'
export { default as FNavbar } from '@/components/navbar'
export { default as FOverlay } from '@/components/overlay'
export { default as FPagination } from '@/components/pagination'
export { default as FPlayer } from '@/components/player'
export { default as FPopover } from '@/components/popover'
export { default as FPopup } from '@/components/popup'
export { default as FRaffle } from '@/components/raffle'
export { default as FScroll } from '@/components/scroll'
export { default as FScrollbar } from '@/components/scrollbar'
// _____TPL_FLAG_import_____
export { default as FSelect } from '@/components/select'
export { default as FSpace } from '@/components/space'
export { default as FSplayer } from '@/components/splayer'
export { default as FSwipe, SwipeItem as FSwipeItem } from '@/components/swipe'

export { default as FTabbar } from '@/components/tabbar'
export { default as FTable } from '@/components/table'
export { default as FTooltip } from '@/components/tooltip'
